services:
  go-admin-api:
    image: go-admin:latest
    privileged: true
    restart: always
    ports:
      - ${DEV_BACKEND_PORT:-18123}:${DEV_BACKEND_PORT:-18123}
    volumes:
      - ./config/:/go-admin-api/config/
      - ./static/:/go-admin-api/static/
      - ./temp/:/go-admin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge
