settings:
    application:
        enabledp: false
        host: 0.0.0.0
        mode: prod
        name: go-admin
        port: 18123
        readtimeout: 1
        writertimeout: 300
    cache:
        redis:
            addr: 127.0.0.1:16379
            db: 0
    database:
        driver: postgres
        source: host=127.0.0.1 port=15432 user=go_admin_dev password=go_admin_dev dbname=go_admin_dev sslmode=disable TimeZone=Asia/Shanghai
    extend:
        demo:
            name: data
        ops:
            environments: []
            taskTimeoutSeconds: 900
    gen:
        dbname: go_admin_dev
        frontpath: ../go-admin-ui/src
    jwt:
        secret: b6e17a3cfbdd6980c3c05edf7f621c0241ffd1b8eb20c5ab59b2fcb071e7df00
        timeout: 3600
    locker:
        redis: {}
    logger:
        enableddb: false
        level: info
        path: temp/logs
        stdout: ""
    queue:
        memory:
            poolSize: 100
